services:
  - type: web
    name: kosge-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Will be set in Render dashboard
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
